### ISSUE TITLE
Multiplayer doesn't work

### ISSUE THREAD

**Issue by Darksimus1** [AlizerUncaged/GDM-Windows#7]
![image](https://user-images.githubusercontent.com/50050567/131129798-dc239396-de37-4fd1-a884-7e4c4e4be7db.png)
![image](https://user-images.githubusercontent.com/50050567/131129896-c0bc1a0a-a075-4702-afec-931d2dcca4da.png)
Errors appear on startup
OS: Windows 10 Enterprise LTSC

**Comment by Dragon77mathbye** [comment]
It might be your antivirus quarantining the files, check there

**Comment by Dycool** [comment]
It could be the antivirus or maybe Visual C++ is missing, try installing vc_redist.x64 here
https://www.microsoft.com/en-us/download/details.aspx?id=48145

**Comment by AlizerUncaged** [comment]
hello guys whats up

**Comment by Darksimus1** [comment]
> It could be the antivirus or maybe Visual C++ is missing, try installing vc_redist.x64 here
> https://www.microsoft.com/en-us/download/details.aspx?id=48145

Antivirus disabled (with Windows Security) and...
![image](https://user-images.githubusercontent.com/50050567/132125928-d62316a4-6d6c-436b-8a09-768f241c5310.png)

**Comment by Darksimus1** [comment]
> hello guys whats up

everything's fine, how're you?

**Comment by Dycool** [comment]
hmm did u try x86 too?

**Comment by Darksimus1** [comment]
> hmm did u try x86 too?

Thanks, it's working now

**Comment by AlizerUncaged** [comment]
![awesome](https://i.ibb.co/pjrrLQh/Remini20210411175554054.jpg)

**Comment by CarFanatic23** [comment]
https://camo.githubusercontent.com/b03bac9db72e89cf2bd79db86483d0b8ce17cd4a5f1d73bd70b3d5d8cc26666b/68747470733a2f2f692e6962622e636f2f706a72724c51682f52656d696e6932303231303431313137353535343035342e6a7067
