### ISSUE TITLE
Edge not letting me open it

### ISSUE THREAD

**Issue by Muwqas** [AlizerUncaged/GDM-Windows#9]
NO MATTER WHAT I DO IT SAYS UNABLE TO DOWNLOAD, VIRUS DETECTED >:(>:(>:(

**Comment by Muwqas** [comment]
\aaaaaaaaaaaaaaaaaaaaaAAAAAAAAAAAAAAAAAAAAAAAAAA

**Comment by Muwqas** [comment]
AWFEVKJ ADSKLJ asdh ieAMH D8qu d80weqmu e8mAsaEDHaud jweD 23r;3qj r;.O 23RJOOP[IR io[pr o32pr wp3qlk3 e,3qro[3w RIw4pr iW3[ NRI wiop[r mir tio4wPOIP4[ ,RWE0[0TM WQ0-Qrtrwyrbweciberbywqecbyq4wcctbuuywe4ytetMX,TQEGRRCXOPI M,GERIO08MU0GR3KV8 T9V TC4I#p Iww [ouf dgihghouhouwruhtcuerwynceyntunywyeuntnrunyecnywnywer8cyrcweyywyuwryyccyuyyeeynun wcecyugtrenyytrnyycrewnyxwaermlcwraucvawre4fw sdsfdv gervergv aesrc werv o fdserstv erv evwr ówe rv

**Comment by Muwqas** [comment]
bvc

**Comment by Muwqas** [comment]
gdsf

**Comment by Muwqas** [comment]
gdm bad

**Comment by AlizerUncaged** [comment]
lol

**Comment by CodeBoi00** [comment]
lol disable nticirus

**Comment by CodeBoi00** [comment]
adntivirus*

**Comment by CarFanatic23** [comment]
antivirus???

**Comment by BowserLover** [comment]
this mans MAD

**Comment by Muwqas** [comment]
u guys sayin disable antivirus
no
there is no disable

**Comment by koweret** [comment]
i was mad lmao
